language: php
php:
  - 7.2
  - 7.3
  - 7.4
script:
  - phpunit tests --coverage-text --coverage-clover=coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
