name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  installAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/phpunit
      env:
        YANDEX_ACCOUNT: ${{ secrets.YANDEX_ACCOUNT }}
        YANDEX_CLIENT_ID: ${{ secrets.YANDEX_CLIENT_ID }}
        YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
